# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "andreina-test-app"
client_id = "623525f4f39a644fabbda6e95f2b8440"
application_url = "https://congratulations-croatia-indonesia-cultural.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://congratulations-croatia-indonesia-cultural.trycloudflare.com/auth/callback",
  "https://congratulations-croatia-indonesia-cultural.trycloudflare.com/auth/shopify/callback",
  "https://congratulations-croatia-indonesia-cultural.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "andreina-dev-store.myshopify.com"
